export const path = {
    WELLCOME: '/',
    HOME: '/home',
    REGISTER: '/register',
    LOGIN: '/login',
    HOROSCOPE: '/horroscope',
    HOROSCOPESAVE: '/horroscopesave',
    CALENDAR: '/calendar',
    FAQPAGE: '/faqs',
    CALENDARCHANGE: '/calendar-change',
    USERINFOR: '/user-info',
    POSTDETAIL: '/post-detail',
    NOTIF: '/notif',
    HAN: '/han',
};
